<?php
/**
 * Created by PhpStorm.
 * User: MXS34
 * Date: 15.01.2017
 * Time: 14:29
 */

namespace app\modules\chat\controllers;

use app\modules\chat\models\{ DialogProperties };
use app\modules\chat\services\{ DialogRepository, DialogFactory} ;
use yii\filters\{ AccessControl, VerbFilter, auth\QueryParamAuth };

use yii\web\Controller;
use yii\base\Exception;

class DefaultController extends Controller
{
    const  DIALOGS_PER_PAGE   = 10;
    const  MESSAGES_PER_PAGE  = 12;

    /** @var DialogRepository */
    protected $dialogRepository;

    /** @var DialogFactory */
    protected $dialogFactory;


    public function init() {
        parent::init();
    }

    public function beforeAction($action) {
        $this->dialogRepository = DialogRepository::getInstance();
        $this->dialogFactory    = DialogFactory::getInstance();

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function  behaviors ()
    {
        return [
            'authenticator' => [
                'class' => QueryParamAuth::class,
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'create-dialog' => ['post'],
                    'set-dialog-properties' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['user']
                    ]
                ]
            ]
        ];
    }


    public function  actionIndex (){
        echo "Chat!";
    }


    public function DeleteDialog($id){
        try{
            $dialog = $this->dialogRepository->findDialogById($id);
        } catch (Exception $e){
            \Yii::$app->session->setFlash('error', $e->getMessage());
            return $this->redirect('index');
        }

        $this->dialogRepository->deleteDialog($dialog);
        \Yii::$app->session->setFlash('success', "Dialog " . $dialog->getTitle() . " has been deleted.");
        return $this->redirect('index');
    }

}









